name: 'Terraform Deploy'

on:
  push:
    branches:
      - main  # This runs the workflow when you push changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust the Terraform version as needed
      - name: Configure Terraform Backend
        run: |
          echo "terraform {
            backend \"local\" {
              path = \"terraform.tfstate\"
            }
          }" > backend.tf

      - name: 'Azure login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init

      - name: Check if Resource Group Exists
        id: rg_check
        run: |
          az group show --name vm_sql_rg123 || echo "Not found"
      
      - name: Import Resource Group if Exists
        if: steps.rg_check.outputs.rg_exists == 'true'
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/189548b6-6700-43c9

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend.tf terraform.tfstate
          git commit -m "Update Terraform state"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/aaidapa96/vmsql.git HEAD:main
      
